---
########################################################################
# This file configures logging for the idm-manager program.
########################################################################
version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  extended:
    format: '%(asctime)s - name=%(name)s - file=%(filename)s - linenum=%(lineno)s - %(levelname)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  dtg:
     pattern: "CUSTOM LOG FORMAT %p [%c] %s%e%n"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: extended
    filename: 'logs/idm-manager.log'
    when: 'H'
    backupCount: 3

root:
  level: INFO
  handlers: [console, file ]
  propagate: true
